version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
  fluent-bit:
    image: fluent/fluent-bit:1.9.10
    command: --config=/etc/fluent-bit/fluent-bit.conf
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./fluentbit:/etc/fluent-bit
    depends_on:
      - nginx
      - clickhouse-server
  clickhouse-server:
    image: clickhouse/clickhouse-server:22.8-alpine
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_PASSWORD=123456
    volumes:
      - ./clickhouse/sql/:/docker-entrypoint-initdb.d/
      - ./clickhouse/data/:/var/lib/clickhouse/
      - ./clickhouse/log/:/val/log/clickhouse-server/